# Generated by Django 3.1.1 on 2023-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20230620_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
