# Generated by Django 3.1.1 on 2023-06-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
